name: honeysat-api-dev-env-p11
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pybamm
    - pybamm[jax]
    - skyfield
    - numpy==1.26.4
    - scipy
    - landsatxplore
    - pyzmq
    - pyIGRF
    - pymongo
    - pillow
    - matplotlib
